### PR TITLE
Expand mathematics on exponential functions

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Explain how quantum mechanics models both wave functions over potentials and exponential decrease within potentials.

Perhaps @felixdoerre could quickly look over this?

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
> Probably fusion with last line of the QM-chapter

You mean just before the operators start? Could fit there, yes.

**Comment by parttimenerd** [comment]
It's a bit to verbose in my opinion.
But it's probable meaningful for other people. I would too move it to the QM section.

**Comment by lucaswerkmeister** [comment]
> write that it's that "k" and that "\kappa"="-i k" (?)

I don’t follow. `k` and `κ` are both rational, how can `κ=-ik` be?

**Comment by parttimenerd** [comment]
No. `k` is complex, if `V > E`. Then `k = i \sqrt{…}` (the square root part being real. Therefore `κ = - ik = \sqrt{…}` is also a real value.

**Comment by lucaswerkmeister** [comment]
Closing, superseded by #29.

**Pull request closed without merging**
